@flashcardId = 218291e9-f277-4c02-b020-3121b860267d
@userId = d1c23c75-0930-4329-8c5b-600c46ee5f3c
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMWMyM2M3NS0wOTMwLTQzMjktOGM1Yi02MDBjNDZlZTVmM2MiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwibmFtZSI6IkFkbWluIiwiaWF0IjoxNzMyMzc4NzQxLCJleHAiOjE3MzI0NjUxNDF9.MMFhS2FegOTaqAxh_KZUAxV5t4d78PlIDpC_u8zMpKs

### Generate flashcard content
POST http://localhost:3000/flashcards/generate
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "subject": "História",
    "question": "O que foi a Revolução Russa"
}

### Find all flashcards
GET http://localhost:3000/flashcards
Authorization: Bearer {{accessToken}}

### Find all due flashcards
GET http://localhost:3000/flashcards?due=true
Authorization: Bearer {{accessToken}}

### Find all upcoming flashcards
GET http://localhost:3000/flashcards?upcoming=true
Authorization: Bearer {{accessToken}}

### Find a particular flashcard
GET http://localhost:3000/flashcards/{{flashcardId}}
Authorization: Bearer {{accessToken}}

### Create a new flashcard
POST http://localhost:3000/flashcards
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "subject": "História",
    "question": "Revolução Russa",
    "answer": "Resposta"
}

### Review flashcard
POST http://localhost:3000/flashcards/review/{{flashcardId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "result": 1
}

### Update a flashcard
PATCH http://localhost:3000/flashcards/{{flashcardId}}
Authorization: Bearer {{accessToken}}
content-type: application/json

{
    "question": "Outra pergunta",
    "answer": "Uma nova resposta",
    "shared": true
}

### Delete a flashcard with given id
DELETE http://localhost:3000/flashcards/{{flashcardId}}
Authorization: Bearer {{accessToken}}