@flashcardId = c0ae3c3e-8c95-406d-8b58-7ef87c3aa748
@userId = d1c23c75-0930-4329-8c5b-600c46ee5f3c
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMWMyM2M3NS0wOTMwLTQzMjktOGM1Yi02MDBjNDZlZTVmM2MiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwibmFtZSI6IkFkbWluIiwiaWF0IjoxNzMxMTkxNzI5LCJleHAiOjE3MzEyNzgxMjl9.WILdbM2D_jNb2WL8pjVWabq6kSsi3JC5XdG1pWaYg8w

### Find all flashcards
GET http://localhost:3000/flashcards
Authorization: Bearer {{accessToken}}

### Find all due flashcards
GET http://localhost:3000/flashcards?due=true
Authorization: Bearer {{accessToken}}

### Find all upcoming flashcards
GET http://localhost:3000/flashcards?upcoming=true
Authorization: Bearer {{accessToken}}

### Find a particular flashcard
GET http://localhost:3000/flashcards/{{flashcardId}}

### Create a new flashcard
POST http://localhost:3000/flashcards
Content-Type: application/json

{
    "userId": "{{userId}}",
    "title": "Revolução Russa",
    "subject": "História",
    "front": "Pergunta",
    "back": "Resposta"
}

### Review flashcard
POST http://localhost:3000/flashcards/review/{{flashcardId}}
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "result": 1
}

### Update a flashcard
PATCH http://localhost:3000/flashcards/{{flashcardId}}
content-type: application/json

{
    "title": "Outra pergunta",
    "content": "Uma nova resposta"
}

### Delete a flashcard with given id
DELETE http://localhost:3000/flashcards/{{flashcardId}}