services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    volumes:
      - ./:/app

  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: studynest
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
