### Hello World
GET http://localhost:3000

### List all notes
GET http://localhost:3000/notes

### List a note
GET http://localhost:3000/notes/7f3ad2bc25ac4ba19a44b9ef135adf42

### Create a new note
POST http://localhost:3000/notes
Content-Type: application/json

{
    "title": "Revolução Russa",
    "subject": "História",
    "content": "Um texto qualquer"
}
