@userId = d1c23c75-0930-4329-8c5b-600c46ee5f3c
@userEmail = admin@example.com
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkMWMyM2M3NS0wOTMwLTQzMjktOGM1Yi02MDBjNDZlZTVmM2MiLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwibmFtZSI6IkFkbWluIiwiaWF0IjoxNzMwNjYwNTcxLCJleHAiOjE3MzA2NjQxNzF9.5-5zEfHyNh9VCqGbFhqLRzsT6Dwt3DjM3I0IVO6ONP4

### Find a particular user with a given ID
GET http://localhost:3000/users/{{userId}}

### Find all users
GET http://localhost:3000/users

### Get user profile
GET http://localhost:3000/users/profile
Authorization: Bearer {{accessToken}}

### Find all users with a given email
GET http://localhost:3000/users?email={{userEmail}}

### Delete a user given id
DELETE http://localhost:3000/users/{{userId}}

### Update a user
PATCH http://localhost:3000/users/{{userId}}
content-type: application/json

{
  "email": "{{userEmail}}",
  "name": "Jonah"
}