@userId = d1c23c75-0930-4329-8c5b-600c46ee5f3c
@userEmail = admin@example.com
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZGI2NTMxMC1hMGUwLTRiMWUtOGY4Ni0xNzNlMTRmNjUyYWEiLCJlbWFpbCI6ImpvbmFzQGV4YW1wbGUuY29tIiwibmFtZSI6bnVsbCwiaWF0IjoxNzMyMTM3MjQzLCJleHAiOjE3MzIyMjM2NDN9.DPqLR9-Evcjkx2HvXKuzkBYrSWiZ6224cisfbCMT4xE

### Find a particular user with a given ID
GET http://localhost:3000/users/{{userId}}

### Find all users
GET http://localhost:3000/users

### Get user profile
GET http://localhost:3000/users/profile
Authorization: Bearer {{accessToken}}

### Find all users with a given email
GET http://localhost:3000/users?email={{userEmail}}

### Delete a user given id
DELETE http://localhost:3000/users/{{userId}}

### Update a user
PATCH http://localhost:3000/users/{{userId}}
Authorization: Bearer {{accessToken}}
content-type: application/json

{
  "email": "{{userEmail}}",
  "name": "Jonah"
}