@userId = f94a644b-8c66-4570-9e58-92a19fe2f9c7
@userEmail = test4@abcd.com
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmOTRhNjQ0Yi04YzY2LTQ1NzAtOWU1OC05MmExOWZlMmY5YzciLCJlbWFpbCI6InRlc3Q0QGFiY2QuY29tIiwibmFtZSI6IkpvbmFoIiwiaWF0IjoxNzI5NDYzODQ1LCJleHAiOjE3Mjk0Njc0NDV9.PcW8aQNIcUBS1K-lXDlBz0biruPGxLMCARkRsp8eOIY

### Find a particular user with a given ID
GET http://localhost:3000/users/{{userId}}

### Find all users
GET http://localhost:3000/users

### Get user profile
GET http://localhost:3000/users/profile
Authorization: Bearer {{accessToken}}

### Find all users with a given email
GET http://localhost:3000/users?email={{userEmail}}

### Delete a user given id
DELETE http://localhost:3000/users/{{userId}}

### Update a user
PATCH http://localhost:3000/users/{{userId}}
content-type: application/json

{
  "email": "{{userEmail}}",
  "name": "Jonah"
}