@noteId = b992b89d-aa92-4a4b-9610-bb633409b60c
@userId = d1c23c75-0930-4329-8c5b-600c46ee5f3c
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3MTBiMDZlZS0wOWIyLTRjMDgtOWVmYy1hNDk2ODI2MzQ4N2IiLCJlbWFpbCI6ImFkbWluN0BleGFtcGxlLmNvbSIsIm5hbWUiOm51bGwsImlhdCI6MTczMjA1MTA5NCwiZXhwIjoxNzMyMTM3NDk0fQ.oYv7QK00uc9C_QJ-p7s-oWBAYyNt5vIyNkAxTXmkBGU

### Generate note content
POST http://localhost:3000/notes/generate
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "subject": "História",
    "title": "Revolução Russa"
}

### Find all notes
GET http://localhost:3000/notes
Authorization: Bearer {{accessToken}}

### Find a particular note
GET http://localhost:3000/notes/{{noteId}}
Authorization: Bearer {{accessToken}}

### Create a new note
POST http://localhost:3000/notes
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "title": "Revolução Russa",
    "subject": "História",
    "content": "Um texto qualquer"
}

### Update a note
PATCH http://localhost:3000/notes/{{noteId}}
Authorization: Bearer {{accessToken}}
content-type: application/json

{
    "title": "Revolução Soviética",
    "content": "Um novo texto qualquer"
}

### Delete a note with given id
DELETE http://localhost:3000/notes/{{noteId}}
Authorization: Bearer {{accessToken}}